# These are supported funding model platforms

github: [ikigailabseth]
custom: ["https://etherscan.io/enslookup-search?search=ikigailabseth.eth", "https://polygonscan.com/address/0xF6E8156B3001C177C6aA35D90F7D643FF52a960d"]
